[pytest]
markers =
    login : marks tests as part of the login feature
    inventory : marks tests as part of the inventory feature
    product_detail : marks tests as part of the product detail feature
    checkout : marks tests as part of the checkout flow or feature
    cart : marks tests as part of the cart feature
    nav : marks tests as part of the site navigation
    testcase_id: marker to associate automated test with a manual test
testpaths = tests